services:
  insightface-gpu:
    build: 
      context: ./InsightFace-REST
      dockerfile: Dockerfile_trt
    env_file:
      - InsightFace-REST/insightface.env
      - .env
    ports: 
      - "$INSIGHTFACE_OUTER_PORT:$INSIGHTFACE_INNER_PORT"
    healthcheck:
      test: ["CMD", curl -f http://localhost:$INSIGHTFACE_OUTER_PORT/info || exit 1]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./InsightFace-REST/models
        target: /models
      - type: bind
        source: ./InsightFace-REST/api_trt
        target: /api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  insightface-cpu:
    build:
      context: ./InsightFace-REST
      dockerfile: Dockerfile_cpu
    env_file:
      - InsightFace-REST/insightface.env
      - .env
    ports:
      - "$INSIGHTFACE_OUTER_PORT:$INSIGHTFACE_INNER_PORT"
    healthcheck:
      test: [ "CMD", curl -f http://localhost:$INSIGHTFACE_OUTER_PORT/info || exit 1 ]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./InsightFace-REST/models
        target: /models
      - type: bind
        source: ./InsightFace-REST/api_trt
        target: /api

  backend:
    env_file:
      - backend/backend.env
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "$BACKEND_OUTER_PORT:$BACKEND_INNER_PORT"

  redis:
    image: redis:6
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "$REDIS_PORT"
    command: "redis-server /usr/local/etc/redis/redis.conf --port $REDIS_PORT"

  tgbot:
    env_file:
      - telegrambot/tgbot.env
      - .env
    build:
      context: ./telegrambot
      dockerfile: Dockerfile