services:
  insightface:
    build: 
      context: ./InsightFace-REST
      dockerfile: Dockerfile_trt
    ports: 
      - "${START_PORT}:${PORT}"
    healthcheck:
      test: ["CMD", curl -f http://localhost:18081/info || exit 1]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./InsightFace-REST/models
        target: /models
      - type: bind
        source: ./InsightFace-REST/api_trt
        target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"